global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "identity"
    metrics_path: /metrics
    static_configs:
      - targets: ["identity:8000"]

  - job_name: "project"
    metrics_path: /metrics
    static_configs:
      - targets: ["project:8000"]

  - job_name: "task"
    metrics_path: /metrics
    static_configs:
      - targets: ["task:8000"]
